# Generated by Django 3.1.4 on 2020-12-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_tracking',
            field=models.BooleanField(default=False),
        ),
    ]
